---
# Name: Install and configure exim MTA

- name: Install exim4
  apt: 
    name:
      - exim4-base
      - exim4-daemon-heavy
    state: latest

- name: Configure stored debconf options (update-exim4.conf.conf)
  template:
    src: update-exim4.conf.conf.j2
    dest: /etc/exim4/update-exim4.conf.conf
    owner: root
    group: root
    mode: '0644'
  notify: run update-exim4.conf

- name: Configure our own override options
  template:
    src: exim4.conf.localmacros.j2
    dest: /etc/exim4/exim4.conf.localmacros
    owner: root
    group: root
    mode: '0644'
  notify: run update-exim4.conf

- name: Set our mailname
  template:
    src: mailname.j2
    dest: /etc/mailname
    owner: root
    group: root
    mode: '0644'
  
- name: Configure /etc/aliases for local mail
  template:
    src: aliases.j2
    dest: /etc/aliases
    owner: root
    group: root
    mode: '0644'

# Symlinks for exim SSL to hopefully work
- name: Set up SSL cert symlink
  file:
    src: /etc/letsencrypt/live/mail.po1.plug.org.au/cert.pem
    dest: /etc/exim4/exim.crt
    owner: root
    group: root
    mode: '0644'
    state: link

- name: Set up SSL key symlink
  file:
    src: /etc/letsencrypt/live/mail.po1.plug.org.au/privkey.pem
    dest: /etc/exim4/exim.key
    owner: root
    group: root
    mode: '0644'
    state: link
